apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vsphere-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: vsphere-csi
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: vsphere-tmm
        namespace: flux-system
  values:
    global:
      config:
        existingSecret: vsphere-config-secret
